name: BookingAhead
favicon: null
layout_spectrum: 0.74729
typography_spectrum: 0.5009
title: BookingAhead
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.5
  lightness: 0.28933627833612263
  saturation: 0.25
  rhythmicContrast: 0.03318165452219546
purpose: []
